name:                journal
version:             0.1.0.0
github:              "githubuser/journal"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2025 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/journal#readme>

dependencies:
- base >= 4.7 && < 5
- process >= 1.6
- directory >= 1.3
- time >= 1.12
- filepath >= 1.4
- brick >= 2.0
- vty >= 6.2
- vector >= 0.13
- mtl >= 2.3
- microlens >= 0.4
- microlens-mtl >= 0.2
- text >= 2.1
- microlens-th >= 0.4
- random >= 1.2

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  journal:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - journal

tests:
  journal-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - journal
